# Generated by Django 4.2.1 on 2023-05-23 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата удаления')),
                ('summary', models.CharField(max_length=128, verbose_name='Проблема')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('due_date', models.DateTimeField(verbose_name='Крайний срок')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Описание')),
                ('status', models.CharField(blank=True, choices=[('open', 'open'), ('overdue', 'overdue'), ('solved', 'solved'), ('closed', 'closed')], default='open', max_length=10, verbose_name='Статус')),
                ('counter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='vehicles.counter', verbose_name='Счетчик')),
                ('creator', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, related_name='service_issues', to=settings.AUTH_USER_MODEL, verbose_name='Ответственные лица')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_issues', to='vehicles.vehicle', verbose_name='ТС')),
            ],
            options={
                'verbose_name': 'Проблема',
                'verbose_name_plural': 'Проблемы',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата удаления')),
                ('order', models.IntegerField(blank=True, default=None, null=True, verbose_name='Порядковый номер')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('creator', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сервисная задача',
                'verbose_name_plural': 'Сервисные задачи',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата удаления')),
                ('start_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата окончания')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('counter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='vehicles.counter', verbose_name='Счетчик')),
                ('creator', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('issues', models.ManyToManyField(blank=True, to='maintenance.issue', verbose_name='Проблемы')),
                ('tasks', models.ManyToManyField(blank=True, to='maintenance.task', verbose_name='Задачи')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='vehicles.vehicle', verbose_name='ТС')),
            ],
            options={
                'verbose_name': 'Сервисная запись',
                'verbose_name_plural': 'Сервисные записи',
            },
        ),
    ]
