# Generated by Django 4.1.7 on 2023-04-19 11:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Марка транспортного средства',
                'verbose_name_plural': 'Марки Транспортных средств',
            },
        ),
        migrations.CreateModel(
            name='CarBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Тип Кузова',
                'verbose_name_plural': 'Тип Кузовов',
            },
        ),
        migrations.CreateModel(
            name='CarClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Класс Автотранспорта',
                'verbose_name_plural': 'Классы Автотранспорта',
            },
        ),
        migrations.CreateModel(
            name='CarGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Штатная группа',
                'verbose_name_plural': 'Штатные группы',
            },
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Тип транспортного средства',
                'verbose_name_plural': 'Типы Транспортных средств',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Цвет Автотранспорта',
                'verbose_name_plural': 'Цвета Автотранспорта',
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер распределения')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата распределения')),
            ],
            options={
                'verbose_name': 'Распределение',
                'verbose_name_plural': 'Распределения',
            },
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=16, null=True, verbose_name='Номер Двигателя')),
                ('model', models.CharField(blank=True, max_length=15, null=True, verbose_name='Модель двигателя т/c')),
                ('power', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Мощность двигателя т/c')),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Объем двигателя т/с')),
            ],
            options={
                'verbose_name': 'Двигатель Т/C',
                'verbose_name_plural': 'Двигатели Т/C',
            },
        ),
        migrations.CreateModel(
            name='GasolineBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
                ('code', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Марка Бензина',
                'verbose_name_plural': 'Марки бензина',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Служба эксплуатации автомобиля',
                'verbose_name_plural': 'Службы эксплутации автомобиля',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Завод Изготовитель',
                'verbose_name_plural': 'Заводы Изготовителя',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организаций',
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер тех. паспорта')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи тех. паспорта')),
            ],
            options={
                'verbose_name': 'Тех. паспорт',
                'verbose_name_plural': 'Тех. паспорта',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('code', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Организ., выдавшая наряд',
                'verbose_name_plural': 'Организ., выдавшая наряд',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=16, null=True, verbose_name='Номер накладной')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата накладной')),
            ],
            options={
                'verbose_name': 'Накладная',
                'verbose_name_plural': 'Накладные',
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=35, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('chef', models.CharField(blank=True, max_length=35, null=True)),
                ('pct_city', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99)])),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.structure')),
            ],
            options={
                'verbose_name': 'Подразделение-владелец транспорта',
                'verbose_name_plural': 'Подразделения-владельцы транспорта',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Инвентарный номер')),
                ('chass_number', models.CharField(blank=True, max_length=8, null=True, verbose_name='Номер Шасси')),
                ('body_number', models.CharField(blank=True, max_length=8, null=True, verbose_name='Номер Кузова')),
                ('year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Год выпуска')),
                ('sign', models.CharField(blank=True, max_length=16, null=True, verbose_name='Номерной государственной регистрации')),
                ('sign1', models.CharField(blank=True, max_length=16, null=True, verbose_name='Реестровый номер')),
                ('sign2', models.CharField(blank=True, max_length=16, null=True, verbose_name='Дубль 2')),
                ('sign_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи номерного знака')),
                ('exploitation_date', models.DateField(blank=True, null=True, verbose_name='Дата ввода в эксплутацию')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Балансовая стоимость')),
                ('source_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='Номер Фондового извещения')),
                ('source_date', models.DateField(blank=True, null=True, verbose_name='Дата документа')),
                ('transfer_date', models.DateField(blank=True, null=True, verbose_name='Дата передачи в подразделение')),
                ('del_date', models.DateField(blank=True, null=True, verbose_name='Дата списания')),
                ('mileage_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Месячная норма пробега')),
                ('fuel_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Норма расхода топлива на 100 км')),
                ('id_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Идентификационный номер')),
                ('climate_control', models.BooleanField(blank=True, null=True, verbose_name='Наличие системы Климат контроль')),
                ('base_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Базовая норма расхода топлива')),
                ('identifier_fuel_rate', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Инд. процент баз. нормы расхода топлива')),
                ('category', models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1, null=True, verbose_name='Категория автомобиля')),
                ('trust_date', models.DateField(blank=True, null=True, verbose_name='Дата действия страхавого полиса')),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='Дата действия технического осмотра')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата ввода')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carbody', verbose_name='Тип Кузова')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.brand', verbose_name='Марка')),
                ('car_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carclass', verbose_name='Класс автомобиля')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.color', verbose_name='Цвет автомобиля')),
                ('distribution', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.distribution', verbose_name='Распределение')),
                ('duty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.maintenanceservice', verbose_name='Служба эксплутации')),
                ('engine', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.engine')),
                ('gasoline_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.gasolinebrand', verbose_name='Марка бензина')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.cargroup', verbose_name='Штатная группа')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.manufacturer', verbose_name='Завод-Изготовитель')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.structure', verbose_name='Подразделение-владелец транспорта')),
                ('passport', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.passport', verbose_name='Тех. паспорт')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.source', verbose_name='Источник получения')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.cartype', verbose_name='Тип транспорта')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.warehouse', verbose_name='Склад')),
                ('waybill', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.waybill', verbose_name='Накладная')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
