# Generated by Django 4.1.7 on 2023-04-19 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_structure_chef_remove_structure_pct_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='code',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='inventory_number',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99999)], verbose_name='Инвентарный номер'),
        ),
    ]
