# Generated by Django 4.1.7 on 2023-04-19 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_structure_code_alter_car_inventory_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='duty',
            new_name='service',
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.engine', verbose_name='Двигатель Т/С'),
        ),
    ]
