# Generated by Django 4.1.7 on 2023-04-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_brand_code_alter_carbody_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='code',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
