# Generated by Django 4.2 on 2023-04-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
