# Generated by Django 4.2.1 on 2023-05-08 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_fueltype_options_expensetype_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='vehicles.vehicle'),
        ),
    ]
