# Generated by Django 4.1.7 on 2023-04-22 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_historicalcar_engine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcar',
            name='engine',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cars.engine', verbose_name='Двигатель Т/С'),
        ),
        migrations.AddField(
            model_name='historicalcar',
            name='passport',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cars.passport', verbose_name='Тех. паспорт'),
        ),
    ]
