# Generated by Django 4.1.7 on 2023-04-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_gov_number_alter_car_register_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='carbody',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='carclass',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='cargroup',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='cartype',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='gasolinebrand',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='maintenanceservice',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
